name: SBI-tutorial
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - pip
  - numpy
  - jupyterlab
  - ipykernel
  - ipywidgets
  - pip:
    - matplotlib
    - seaborn
    - emcee
    - ultranest
    - corner
    - swyft
    - tensorflow
    - tensorflow-probability
    - torch
    - https://github.com/dprelogo/conditional_kde/tarball/master
    - https://github.com/dprelogo/21cmLikelihoods/tarball/master