name: SBI-tutorial
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - pip
  - numpy
  - corner
  - ultranest
  - jupyterlab
  - ipykernel
  - ipywidgets
  - emcee
  - pip:
    - swyft
    - tensorflow
    - tensorflow-probability
    - pytorch
    - https://github.com/dprelogo/conditional_kde/tarball/master
    - https://github.com/dprelogo/21cmLikelihoods/tarball/master